controller_joint_names: ['', 'FL_ABAD_JOINT', 'FL_HIP_JOINT', 'FL_KNEE_JOINT', 'FR_ABAD_JOINT', 'FR_HIP_JOINT', 'FR_KNEE_JOINT', 'RR_ABAD_JOINT', 'RR_HIP_JOINT', 'RR_KNEE_JOINT', 'RL_ABAD_JOINT', 'RL_HIP_JOINT', 'RL_KNEE_JOINT', ]
